spring:
  profiles:
    default: local

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-version: 1
    validate-on-migrate: true

  sql:
    init:
      mode: never

  ai:
    openai:
      chat:
        options:
          model: gpt-4o-mini
      embedding:
        options:
          model: text-embedding-3-small
