CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE trouble (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    description TEXT,
    raw_log TEXT,
    status VARCHAR(255),
    actual_cause TEXT,
    solution TEXT,
    reference_link VARCHAR(255),
    archived_at TIMESTAMP(6),
    ai_processing_status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    ai_last_error_code VARCHAR(255),
    ai_last_error_message TEXT,
    ai_processed_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT trouble_status_check
        CHECK (status IN ('OPEN', 'RESOLVED')),
    CONSTRAINT trouble_ai_processing_status_check
        CHECK (ai_processing_status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED'))
);

CREATE TABLE aianalysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trouble_id BIGINT NOT NULL UNIQUE,
    category VARCHAR(255),
    summary TEXT,
    possible_causes TEXT,
    runbook TEXT,
    confidence INTEGER,
    model_name VARCHAR(255),
    prompt_version VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_aianalysis_trouble
        FOREIGN KEY (trouble_id) REFERENCES trouble (id)
);

CREATE TABLE trouble_embedding (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trouble_id BIGINT NOT NULL,
    input_text TEXT NOT NULL,
    embedding vector(1536) NOT NULL,
    model_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uk_trouble_embedding_trouble_id UNIQUE (trouble_id),
    CONSTRAINT fk_trouble_embedding_trouble
        FOREIGN KEY (trouble_id) REFERENCES trouble (id)
);

CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE trouble_tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trouble_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    CONSTRAINT fk_trouble_tag_trouble
        FOREIGN KEY (trouble_id) REFERENCES trouble (id),
    CONSTRAINT fk_trouble_tag_tag
        FOREIGN KEY (tag_id) REFERENCES tag (id)
);

CREATE TABLE retrospective (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trouble_id BIGINT NOT NULL UNIQUE,
    content TEXT,
    lesson TEXT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_retrospective_trouble
        FOREIGN KEY (trouble_id) REFERENCES trouble (id)
);

CREATE INDEX idx_trouble_embedding_embedding_hnsw_cosine
    ON trouble_embedding
    USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE INDEX idx_trouble_active_created_at
    ON trouble (created_at DESC)
    WHERE archived_at IS NULL;

CREATE INDEX idx_trouble_active_status_created_at
    ON trouble (status, created_at DESC)
    WHERE archived_at IS NULL;

CREATE INDEX idx_trouble_archived_created_at
    ON trouble (created_at DESC)
    WHERE archived_at IS NOT NULL;

CREATE INDEX idx_trouble_title_trgm
    ON trouble USING gin (lower(title) gin_trgm_ops);

CREATE INDEX idx_trouble_description_trgm
    ON trouble USING gin (lower(description) gin_trgm_ops);

CREATE INDEX idx_trouble_tag_trouble_id
    ON trouble_tag (trouble_id);

CREATE INDEX idx_trouble_tag_tag_id_trouble_id
    ON trouble_tag (tag_id, trouble_id);
